export const PAGINATION = {
  PROFILES_DEFAULT_LIMIT: 20,
  PROFILES_MAX_LIMIT: 100,
  ADMIN_DEFAULT_LIMIT: 20,
  ADMIN_MAX_LIMIT: 100,
  DEMO_FETCH_LIMIT: 100,
} as const;

export const SUPER_LIKE_DAILY_LIMIT = 3;

export const LIKE_RATE_LIMIT = {
  MAX_LIKES: 30,
  WINDOW_SECONDS: 600,
} as const;

export const LOGIN_LIMITS = {
  MAX_ATTEMPTS: 20,
  LOCKOUT_WINDOW: 15 * 60,
  LOCKOUT_DURATION: 30 * 60,
} as const;

export const REGISTRATION_LIMITS = {
  MAX_PER_HOUR: 5,
  WINDOW_SECONDS: 3600,
} as const;

export const MATCH_ANIMATION_DELAY = 300;

export const SWIPE = {
  THRESHOLD: 120,
  LABEL_THRESHOLD: 60,
  TAP_DISTANCE: 10,
  ANIMATION_DURATION: 500,
  SUPER_LIKE_DURATION: 800,
  CARD_REMOVAL_DELAY: 400,
} as const;

export const SCORING = {
  LIKE_WEIGHT: 10,
  MATCH_WEIGHT: 5,
  ACTIVITY_MATCH_BONUS: 50,
} as const;

export const VALIDATION = {
  NAME_MAX_LENGTH: 100,
  BIO_MAX_LENGTH: 500,
  CITY_MAX_LENGTH: 100,
  INTERESTS_MAX_LENGTH: 500,
  AGE_MIN: 18,
  AGE_MAX: 120,
  MESSAGE_MAX_LENGTH: 2000,
  MOMENT_MAX_LENGTH: 200,
  COMMENT_MAX_LENGTH: 500,
  BLOCK_REASON_MAX_LENGTH: 500,
  REPORT_REASON_MAX_LENGTH: 500,
  REPORT_DETAILS_MAX_LENGTH: 2000,
} as const;

export const TOKEN = {
  BYTE_LENGTH: 32,
  VERIFICATION_EXPIRY_MS: 24 * 60 * 60 * 1000,
  RESET_EXPIRY_MS: 60 * 60 * 1000,
} as const;

export const UPLOAD = {
  MAX_FILE_SIZE: 5 * 1024 * 1024,
  MAX_PHOTOS: 6,
} as const;

export const ACHIEVEMENT_THRESHOLDS = {
  FIRST_LIKE: 1,
  HEART_HUNTER: 10,
  SUPER_STAR: 5,
  FIRST_MATCH: 1,
  POPULAR: 5,
  BELOVED: 10,
  START_OF_JOURNEY: 1,
  PRO: 50,
  SUPER_LIKE_MASTER: 3,
  COLLECTOR: 25,
} as const;

export const MOMENTS = {
  CHARACTER_LIMIT: 200,
  CHARACTER_WARN_THRESHOLD: 20,
  PREVIEW_COMMENTS: 2,
  STORY_PROGRESS_TICK: 2,
  STORY_PROGRESS_MAX: 100,
  STORY_INTERVAL_MS: 100,
  STORY_SWIPE_CLOSE_THRESHOLD: 100,
} as const;

export const AUTO_REPLY = {
  MIN_DELAY: 1500,
  MAX_DELAY: 2500,
  TYPING_MIN: 500,
  TYPING_MAX: 800,
  RATE_LIMIT_MAX: 5,
  RATE_LIMIT_WINDOW: 60,
} as const;

export const REPORT_LIMITS = {
  MAX_PER_HOUR: 10,
  WINDOW_SECONDS: 3600,
} as const;

export const RATE_LIMITS = {
  FORGOT_PASSWORD: { MAX: 3, WINDOW: 3600 },
  VERIFY_EMAIL: { MAX: 3, WINDOW: 3600 },
  CHANGE_PASSWORD: { MAX: 5, WINDOW: 900 },
  TOTP_VERIFY: { MAX: 5, WINDOW: 300 },
  TOTP_REPLAY: { MAX: 1, WINDOW: 300 },
} as const;

export const TOTP = {
  TOKEN_LENGTH: 6,
  TEMP_TOKEN_TTL_MINUTES: 5,
} as const;
