export const PAGINATION = {
  PROFILES_DEFAULT_LIMIT: 20,
  PROFILES_MAX_LIMIT: 100,
  ADMIN_DEFAULT_LIMIT: 20,
  ADMIN_MAX_LIMIT: 100,
  DEMO_FETCH_LIMIT: 100,
  MOMENTS_DEFAULT_LIMIT: 20,
  MOMENTS_MAX_LIMIT: 50,
} as const;

export const SUPER_LIKE_DAILY_LIMIT = 3;

export const LIKE_RATE_LIMIT = {
  MAX_LIKES: 30,
  WINDOW_SECONDS: 600,
} as const;

export const LOGIN_LIMITS = {
  MAX_ATTEMPTS: 20,
  LOCKOUT_WINDOW: 15 * 60,
  LOCKOUT_DURATION: 30 * 60,
} as const;

export const REGISTRATION_LIMITS = {
  MAX_PER_HOUR: 5,
  WINDOW_SECONDS: 3600,
} as const;

export const MATCH_ANIMATION_DELAY = 300;

export const SWIPE = {
  THRESHOLD: 120,
  LABEL_THRESHOLD: 60,
  TAP_DISTANCE: 10,
  ANIMATION_DURATION: 500,
  SUPER_LIKE_DURATION: 800,
  CARD_REMOVAL_DELAY: 400,
} as const;

export const SCORING = {
  LIKE_WEIGHT: 10,
  MATCH_WEIGHT: 5,
  ACTIVITY_MATCH_BONUS: 50,
} as const;

export const VALIDATION = {
  NAME_MAX_LENGTH: 100,
  BIO_MAX_LENGTH: 500,
  CITY_MAX_LENGTH: 100,
  INTERESTS_MAX_LENGTH: 500,
  AGE_MIN: 18,
  AGE_MAX: 120,
  MESSAGE_MAX_LENGTH: 2000,
  MOMENT_MAX_LENGTH: 200,
  COMMENT_MAX_LENGTH: 500,
  BLOCK_REASON_MAX_LENGTH: 500,
  REPORT_REASON_MAX_LENGTH: 500,
  REPORT_DETAILS_MAX_LENGTH: 2000,
} as const;

export const FILTER = {
  AGE_DEFAULT_MIN: 0,
  AGE_DEFAULT_MAX: 99,
} as const;

export const TOKEN = {
  BYTE_LENGTH: 32,
  VERIFICATION_EXPIRY_MS: 24 * 60 * 60 * 1000,
  RESET_EXPIRY_MS: 60 * 60 * 1000,
} as const;

export const UPLOAD = {
  MAX_FILE_SIZE: 5 * 1024 * 1024,
  MAX_PHOTOS: 6,
} as const;

export const ACHIEVEMENT_THRESHOLDS = {
  FIRST_LIKE: 1,
  HEART_HUNTER: 10,
  SUPER_STAR: 5,
  FIRST_MATCH: 1,
  POPULAR: 5,
  BELOVED: 10,
  START_OF_JOURNEY: 1,
  PRO: 50,
  SUPER_LIKE_MASTER: 3,
  COLLECTOR: 25,
} as const;

export const MOMENTS = {
  CHARACTER_LIMIT: 200,
  CHARACTER_WARN_THRESHOLD: 20,
  PREVIEW_COMMENTS: 2,
  STORY_PROGRESS_TICK: 2,
  STORY_PROGRESS_MAX: 100,
  STORY_INTERVAL_MS: 100,
  STORY_SWIPE_CLOSE_THRESHOLD: 100,
} as const;

export const AUTO_REPLY = {
  MIN_DELAY: 1500,
  MAX_DELAY: 2500,
  TYPING_MIN: 500,
  TYPING_MAX: 800,
  RATE_LIMIT_MAX: 5,
  RATE_LIMIT_WINDOW: 60,
} as const;

export const REPORT_LIMITS = {
  MAX_PER_HOUR: 10,
  WINDOW_SECONDS: 3600,
} as const;

export const RATE_LIMITS = {
  FORGOT_PASSWORD: { MAX: 3, WINDOW: 3600 },
  VERIFY_EMAIL: { MAX: 3, WINDOW: 3600 },
  CHANGE_PASSWORD: { MAX: 5, WINDOW: 900 },
  TOTP_SETUP: { MAX: 3, WINDOW: 3600 },
  TOTP_VERIFY: { MAX: 5, WINDOW: 300 },
  TOTP_REPLAY: { MAX: 1, WINDOW: 300 },
  MESSAGE: { MAX: 10, WINDOW: 60 },
  DISLIKE: { MAX: 30, WINDOW: 600 },
  BLOCK: { MAX: 10, WINDOW: 3600 },
  MOMENT: { MAX: 20, WINDOW: 3600 },
  PROFILES: { MAX: 30, WINDOW: 60 },
  ADMIN: { MAX: 20, WINDOW: 60 },
} as const;

export const TOTP = {
  TOKEN_LENGTH: 6,
  TEMP_TOKEN_TTL_MINUTES: 5,
  SECRET_BYTE_LENGTH: 20,
  PERIOD: 30,
  VALIDATE_WINDOW: 1,
  BACKUP_CODE_COUNT: 8,
  BACKUP_CODE_BYTES: 8,
  BACKUP_CODE_LENGTH: 8,
} as const;

export const ANIMATION = {
  HEADER_DURATION: 0.8,
  PULSE_DURATION: 2,
  SPINNER_DURATION: 1,
  STAGGER_BASE: 0.05,
  STAGGER_FAST: 0.04,
  STAGGER_INSTAGRAM: 0.06,
  FEATURE_CARD_STAGGER: 0.1,
  PODIUM_STAGGER_BASE: 0.15,
  ROW_STAGGER: 0.04,
  SETTINGS_STAGGER: 0.07,
  FILTER_DURATION: 0.3,
  EMOJI_PICKER_DURATION: 0.15,
  STORY_OVERLAY_DURATION: 0.25,
  STORY_TEXT_DURATION: 0.35,
  STORY_HINT_DELAY: 1,
  STORY_HINT_DURATION: 0.5,
  FEED_CARD_DURATION: 0.3,
  MATCH_SPARKLES_DELAY: 0.3,
  MATCH_AVATARS_DELAY: 0.5,
  MATCH_BUTTONS_DELAY: 0.7,
  LANDING_HEADER_DELAY: 0.3,
  LANDING_BUTTONS_DELAY: 0.3,
  LANDING_DEMO_DELAY: 0.4,
  LANDING_FEATURES_DELAY: 0.2,
  LANDING_STATS_DELAY: 0.8,
  LANDING_COPYRIGHT_DELAY: 1,
  SENDING_DOTS_DURATION: 1.2,
} as const;

export const SPRING = {
  DETAIL_MODAL_STIFFNESS: 300,
  DETAIL_MODAL_DAMPING: 30,
  CARD_DRAG_STIFFNESS: 200,
  CARD_DRAG_DAMPING: 25,
  MATCH_CARD_STIFFNESS: 200,
  MATCH_CARD_DAMPING: 15,
  ACHIEVEMENT_CARD_STIFFNESS: 260,
  ACHIEVEMENT_CARD_DAMPING: 20,
  ACHIEVEMENT_HOVER_STIFFNESS: 300,
  ACHIEVEMENT_HOVER_DAMPING: 24,
  ACHIEVEMENT_FOOTER_STIFFNESS: 200,
  ACHIEVEMENT_FOOTER_DAMPING: 18,
} as const;

export const SWIPE_EXT = {
  EXIT_X: 300,
  ROTATION_ANGLE: 20,
  DRAG_ROTATION_FACTOR: 0.05,
  BURST_DURATION: 0.8,
  SUPER_LIKE_BURST_DURATION: 1,
} as const;

export const HEARTS = {
  PRNG_ITERATIONS: 105,
  COUNT: 15,
  MIN_SIZE: 12,
  SIZE_RANGE: 20,
  MIN_DURATION: 6,
  DURATION_RANGE: 8,
  DELAY_MULTIPLIER: 10,
  DRIFT_RANGE: 200,
  SPIN_RANGE: 360,
  MIN_OPACITY: 0.15,
  OPACITY_RANGE: 0.25,
} as const;

export const PORT = {
  MAX_ATTEMPTS: 20,
  MAX_PORT: 65536,
  DEFAULT: 3000,
  START: 3000,
} as const;

export const DB = {
  TIMEOUT_MS: 2000,
  PG_PORT: 5432,
  MONGO_PORT: 27017,
} as const;

export const EMOJI = {
  GRID_COLUMNS: 6,
  PICKER_MAX_HEIGHT_VH: 50,
} as const;

export const TIME = {
  MS_PER_MINUTE: 60000,
  MINUTES_PER_HOUR: 60,
  HOURS_PER_DAY: 24,
  RESEND_COOLDOWN_SECONDS: 60,
  RESEND_COOLDOWN_INTERVAL_MS: 1000,
} as const;

export const ONLINE_PRESENCE = {
  ACTIVE_THRESHOLD_MS: 5 * 60 * 1000, // 5 minutes
} as const;

export const BLOCK_REASON = 'Blocked from profile detail' as const;
export const REPORT_REASON = 'Inappropriate behavior' as const;
