import { readFileSync, writeFileSync, existsSync } from 'fs';
import { randomBytes } from 'crypto';
import { detectAvailableDatabases, recommendDatabase, type AvailableDBs } from './auto-detect';

export function parseEnvFile(content: string): Map<string, string> {
  const map = new Map<string, string>();
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx === -1) continue;
    const key = trimmed.slice(0, idx).trim();
    const value = trimmed.slice(idx + 1).trim();
    map.set(key, value);
  }
  return map;
}

export function readEnvFile(path: string): Map<string, string> {
  if (!existsSync(path)) return new Map();
  try {
    const content = readFileSync(path, 'utf-8');
    return parseEnvFile(content);
  } catch {
    return new Map();
  }
}

export async function generateDefaultEnv(
  availableDBs: AvailableDBs,
  port?: number
): Promise<Map<string, string>> {
  const rec = recommendDatabase(availableDBs);
  const appPort = port || 3000;

  const env = new Map<string, string>();
  env.set('DATABASE_URL', rec.url);
  env.set('DB_PROVIDER', rec.provider);
  env.set('JWT_SECRET', randomBytes(32).toString('base64'));
  env.set('NEXT_PUBLIC_APP_URL', `http://localhost:${appPort}`);
  env.set('DEMO_MODE', 'true');
  env.set('NEXT_PUBLIC_DEMO_MODE', 'true');
  env.set('RESEND_API_KEY', 're_xxxxxxxxxxxxx');
  env.set('RESEND_FROM_EMAIL', 'onboarding@resend.dev');

  return env;
}

export function mergeEnvFiles(
  existing: Map<string, string>,
  defaults: Map<string, string>
): { map: Map<string, string>; changed: boolean } {
  const merged = new Map(existing);
  let changed = false;

  for (const [key, value] of defaults) {
    if (!merged.has(key) || merged.get(key) === '') {
      merged.set(key, value);
      changed = true;
    }
  }

  return { map: merged, changed };
}

function formatEnvValue(value: string): string {
  if (value.includes(' ') || value.includes('#') || value.includes('"') || value.includes("'")) {
    return `"${value.replace(/"/g, '\\"')}"`;
  }
  return value;
}

export function writeEnvFile(path: string, env: Map<string, string>): void {
  const lines: string[] = [
    '# Love Compass - Environment Configuration',
    '# Generated by setup script. Update values as needed.',
    '',
    '# Database - choose ONE of the following:',
    '',
    `DATABASE_URL=${formatEnvValue(env.get('DATABASE_URL') || '')}`,
    `DB_PROVIDER=${formatEnvValue(env.get('DB_PROVIDER') || '')}`,
    '',
    '# JWT (for 2FA temp tokens) - Generate a strong secret: openssl rand -base64 32',
    `JWT_SECRET=${formatEnvValue(env.get('JWT_SECRET') || '')}`,
    '',
    '# App',
    `NEXT_PUBLIC_APP_URL=${formatEnvValue(env.get('NEXT_PUBLIC_APP_URL') || '')}`,
    `DEMO_MODE=${formatEnvValue(env.get('DEMO_MODE') || 'true')}`,
    `NEXT_PUBLIC_DEMO_MODE=${formatEnvValue(env.get('NEXT_PUBLIC_DEMO_MODE') || 'true')}`,
    '',
    '# Email (Resend) - Get key from https://resend.com',
    `RESEND_API_KEY=${formatEnvValue(env.get('RESEND_API_KEY') || '')}`,
    `RESEND_FROM_EMAIL=${formatEnvValue(env.get('RESEND_FROM_EMAIL') || 'onboarding@resend.dev')}`,
    '',
  ];

  writeFileSync(path, lines.join('\n'), 'utf-8');
}

export async function ensureEnvFile(envPath = '.env'): Promise<{
  created: boolean;
  merged: boolean;
  path: string;
}> {
  const existing = readEnvFile(envPath);
  const hasExisting = existing.size > 0;

  const availableDBs = await detectAvailableDatabases();
  const port = process.env.PORT
    ? parseInt(process.env.PORT, 10)
    : undefined;

  const defaults = await generateDefaultEnv(availableDBs, port !== undefined && isNaN(port) ? undefined : port);

  if (!hasExisting) {
    writeEnvFile(envPath, defaults);
    return { created: true, merged: false, path: envPath };
  }

  const { map: merged, changed } = mergeEnvFiles(existing, defaults);

  if (changed) {
    writeEnvFile(envPath, merged);
    return { created: false, merged: true, path: envPath };
  }

  return { created: false, merged: false, path: envPath };
}
